class ShowController < ApplicationController

  before_action do
    @posts = []
    @posts << Post.new("A FANTASTIC ENGADGING HEADLINE GOES HERE", "THIS ONE HAS NO IMAGE.jpg", "THE LATEST POST CONTENT")
    @posts << Post.new("ANOTHER COOL POST", "c1.jpg", "Dreamcatcher whatever cred listicle. Squid PBR&B cray, whatever freegan deep v Brooklyn trust fund bespoke iPhone bitters. Ennui brunch flexitarian whatever, YOLO polaroid tattooed +1 tote bag. Neutra wayfarers Thundercats, aesthetic banh mi Schlitz stumptown pour-over bitters literally pug squid YOLO tote bag cliche. Cold-pressed forage typewriter selvage YOLO, Blue Bottle aesthetic leggings 8-bit four loko. Retro cold-pressed paleo whatever asymmetrical, Intelligentsia four dollar toast fingerstache DIY hella scenester messenger bag. Sriracha Helvetica chambray slow-carb Echo Park. Heirloom mumblecore shabby chic deep v, art party small batch umami chillwave quinoa 8-bit Pitchfork you probably haven't heard of them food truck retro. McSweeney's Intelligentsia blog kale chips pork belly, lo-fi cornhole cray. American Apparel food truck actually, ugh fap crucifix photo booth tofu letterpress lo-fi artisan pickled messenger bag Banksy. You probably haven't heard of them mixtape DIY pork belly, Portland XOXO farm-to-table taxidermy McSweeney's drinking vinegar wolf. Drinking vinegar gentrify trust fund food truck, meh asymmetrical Vice. Sriracha Truffaut wayfarers, hoodie sustainable irony jean shorts fingerstache Neutra Carles. Hoodie synth migas, four dollar toast bespoke umami Intelligentsia tousled deep v ugh. Pour-over High Life direct trade, cronut fixie tattooed leggings bespoke master cleanse 8-bit banjo tote bag hella Helvetica. Before they sold out locavore Godard, hashtag Pitchfork lumbersexual mumblecore keffiyeh fanny pack stumptown iPhone. Shabby chic food truck quinoa hoodie sartorial meditation YOLO. IPhone polaroid health goth, pickled normcore locavore Pitchfork tousled heirloom. Squid Blue Bottle bitters flannel, 8-bit authentic Helvetica synth small batch kogi. Trust fund narwhal pop-up letterpress vegan. Narwhal selvage polaroid bicycle rights drinking vinegar, Marfa whatever mustache food.")
    @posts << Post.new("POST TITLE", "c2.jpg", "Squid PBR&B cray, whatever freegan deep v Brooklyn trust fund bespoke iPhone bitters. Ennui brunch flexitarian whatever, YOLO polaroid tattooed +1 tote bag. Neutra wayfarers Thundercats, aesthetic banh mi Schlitz stumptown pour-over bitters literally pug squid YOLO tote bag cliche. Cold-pressed forage typewriter selvage YOLO, Blue Bottle aesthetic leggings 8-bit four loko. Retro cold-pressed paleo whatever asymmetrical, Intelligentsia four dollar toast fingerstache DIY hella scenester messenger bag. Sriracha Helvetica chambray slow-carb Echo Park. Heirloom mumblecore shabby chic deep v, art party small batch umami chillwave quinoa 8-bit Pitchfork you probably haven't heard of them food truck retro. McSweeney's Intelligentsia blog kale chips pork belly, lo-fi cornhole cray. American Apparel food truck actually, ugh fap crucifix photo booth tofu letterpress lo-fi artisan pickled messenger bag Banksy. You probably haven't heard of them mixtape DIY pork belly, Portland XOXO farm-to-table taxidermy McSweeney's drinking vinegar wolf. Drinking vinegar gentrify trust fund food truck, meh asymmetrical Vice. Sriracha Truffaut wayfarers, hoodie sustainable irony jean shorts fingerstache Neutra Carles. Hoodie synth migas, four dollar toast bespoke umami Intelligentsia tousled deep v ugh. Pour-over High Life direct trade, cronut fixie tattooed leggings bespoke master cleanse 8-bit banjo tote bag hella Helvetica. Before they sold out locavore Godard, hashtag Pitchfork lumbersexual mumblecore keffiyeh fanny pack stumptown iPhone. Shabby chic food truck quinoa hoodie sartorial meditation YOLO. IPhone polaroid health goth, pickled normcore locavore Pitchfork tousled heirloom. Squid Blue Bottle bitters flannel, 8-bit authentic Helvetica synth small batch kogi. Trust fund narwhal pop-up letterpress vegan. Narwhal selvage polaroid bicycle rights drinking vinegar.")
    @posts << Post.new("HERE'S ANOTHER LONGER POST TITLE", "c3.jpg", "Dreamcatcher whatever cred listicle. Squid PBR&B cray, whatever freegan deep v Brooklyn trust fund bespoke iPhone bitters. Ennui brunch flexitarian whatever, YOLO polaroid tattooed +1 tote bag. Neutra wayfarers Thundercats, aesthetic banh mi Schlitz stumptown pour-over bitters literally pug squid YOLO tote bag cliche. Cold-pressed forage typewriter selvage YOLO, Blue Bottle aesthetic leggings 8-bit four loko. Retro cold-pressed paleo whatever asymmetrical, Intelligentsia four dollar toast fingerstache DIY hella scenester messenger bag. Sriracha Helvetica chambray slow-carb Echo Park. Heirloom mumblecore shabby chic deep v, art party small batch umami chillwave quinoa 8-bit Pitchfork you probably haven't heard of them food truck retro. McSweeney's Intelligentsia blog kale chips pork belly, lo-fi cornhole cray. American Apparel food truck actually, ugh fap crucifix photo booth tofu letterpress lo-fi artisan pickled messenger bag Banksy. You probably haven't heard of them mixtape DIY pork belly, Portland XOXO farm-to-table taxidermy McSweeney's drinking vinegar wolf. Drinking vinegar gentrify trust fund food truck, meh asymmetrical Vice. Sriracha Truffaut wayfarers, hoodie sustainable irony jean shorts fingerstache Neutra Carles. Hoodie synth migas, four dollar toast bespoke umami Intelligentsia tousled deep v ugh. Pour-over High Life direct trade, cronut fixie tattooed leggings bespoke master cleanse 8-bit banjo tote bag hella Helvetica. Before they sold out locavore Godard, hashtag Pitchfork lumbersexual mumblecore keffiyeh fanny pack stumptown iPhone. Shabby chic food truck quinoa hoodie sartorial meditation YOLO. IPhone polaroid health goth, pickled normcore locavore Pitchfork tousled heirloom. Squid Blue Bottle bitters flannel, 8-bit authentic Helvetica synth small batch kogi. Trust fund narwhal pop-up letterpress vegan. Narwhal selvage polaroid bicycle rights drinking vinegar, Marfa whatever mustache food.")
    @posts << Post.new("OH COOL A POST!", "c4.jpg", "Squid PBR&B cray, whatever freegan deep v Brooklyn trust fund bespoke iPhone bitters. Ennui brunch flexitarian whatever, YOLO polaroid tattooed +1 tote bag. Neutra wayfarers Thundercats, aesthetic banh mi Schlitz stumptown pour-over bitters literally pug squid YOLO tote bag cliche. Cold-pressed forage typewriter selvage YOLO, Blue Bottle aesthetic leggings 8-bit four loko. Retro cold-pressed paleo whatever asymmetrical, Intelligentsia four dollar toast fingerstache DIY hella scenester messenger bag. Sriracha Helvetica chambray slow-carb Echo Park. Heirloom mumblecore shabby chic deep v, art party small batch umami chillwave quinoa 8-bit Pitchfork you probably haven't heard of them food truck retro. McSweeney's Intelligentsia blog kale chips pork belly, lo-fi cornhole cray. American Apparel food truck actually, ugh fap crucifix photo booth tofu letterpress lo-fi artisan pickled messenger bag Banksy. You probably haven't heard of them mixtape DIY pork belly, Portland XOXO farm-to-table taxidermy McSweeney's drinking vinegar wolf. Drinking vinegar gentrify trust fund food truck, meh asymmetrical Vice. Sriracha Truffaut wayfarers, hoodie sustainable irony jean shorts fingerstache Neutra Carles. Hoodie synth migas, four dollar toast bespoke umami Intelligentsia tousled deep v ugh. Pour-over High Life direct trade, cronut fixie tattooed leggings bespoke master cleanse 8-bit banjo tote bag hella Helvetica. Before they sold out locavore Godard, hashtag Pitchfork lumbersexual mumblecore keffiyeh fanny pack stumptown iPhone. Shabby chic food truck quinoa hoodie sartorial meditation YOLO. IPhone polaroid health goth, pickled normcore locavore Pitchfork tousled heirloom. Squid Blue Bottle bitters flannel, 8-bit authentic Helvetica synth small batch kogi. Trust fund narwhal pop-up letterpress vegan. Narwhal selvage polaroid bicycle rights drinking vinegar, Marfa whatever mustache.")
  end

  def blogs # is an action
    @single_post = params[:post].parameterize  # what I named the param in the routes file
    @the_index = @posts.index(@posts.find {|post| post.title.parameterize == params[:post]})   # find the index of the blog post title that matches the url
  end

  def index # is an action, our default page

  end
end


class Post
  attr_accessor :title, :image, :content

  def initialize(title, image, content)
    @title = title
    @image = image
    @content = content
  end

end
